pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build Stage'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Test Stage'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploy Stage'
            }
        }
    }
    post{
        always{
            emailext body: '', subject: 'Summary', to: 'shireesha.kongara@gmail.com'
       }
    }
    
    
}
